#!/usr/bin/env python3
"""Scan OpenViking memories for leaked credentials and redact them.

Runs as a Hermes no-agent cron job: stdout is delivered verbatim, empty stdout = silent.
Walks the user's memory trees over the OpenViking API (as the owner, so rewrites refresh
the vector index), replaces any secret value with a placeholder via /content/write, and
prints one line per fix. Secret values are never printed.

Directory summaries (.overview.md / .abstract.md) are generated by OpenViking and can't be
rewritten over the API; hits there are reported once for manual cleanup.

env / ~/.hermes/.env: OPENVIKING_ENDPOINT, OPENVIKING_API_KEY, OPENVIKING_USER
flags: --dry-run (report only), --roots uri,uri (override scan roots)
"""
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

PLACEHOLDER = "[凭据已移除·ov-secret-scan]"
STATE_FILE = Path.home() / ".hermes" / "scripts" / ".ov_secret_scan_state.json"

# (label, pattern, group holding the secret value)
PATTERNS = [
    ("private-key", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]+?-----END [A-Z ]*PRIVATE KEY-----"), 0),
    ("sk-key", re.compile(r"(?<![A-Za-z0-9])sk-(?:ant-|or-v1-|proj-)?[A-Za-z0-9_-]{20,}"), 0),
    ("apify", re.compile(r"(?<![A-Za-z0-9])apify_(?:proxy|api)_[A-Za-z0-9]{20,}"), 0),
    ("github", re.compile(r"(?<![A-Za-z0-9])(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{20,}|(?<![A-Za-z0-9])github_pat_[A-Za-z0-9_]{20,}"), 0),
    ("slack", re.compile(r"(?<![A-Za-z0-9])xox[baprs]-[A-Za-z0-9-]{10,}"), 0),
    ("google", re.compile(r"(?<![A-Za-z0-9])AIza[0-9A-Za-z_-]{30,}"), 0),
    ("aws", re.compile(r"(?<![A-Za-z0-9])AKIA[0-9A-Z]{16}(?![A-Za-z0-9])"), 0),
    ("url-credentials", re.compile(r"[a-zA-Z][a-zA-Z0-9+.-]*://[^\s/:@<>]+:([^\s/@<>*]{6,})@"), 1),
    ("keyword", re.compile(
        r"(?i)(?:password|passwd|pwd|secret|token|api[_-]?key|access[_-]?key|密码|口令|密钥)"
        r"[\s\"'`]*[:=：]?[\s\"'`]*([A-Za-z0-9_\-+/=.!@#$%^&]{10,})"), 1),
]


def looks_like_secret(label: str, value: str) -> bool:
    if label != "keyword":
        return True
    # keyword matches need a real-looking value: mixed letters+digits, not a path/placeholder
    if value.startswith(("~", "/", "http", "<", "[", "$")) or "*" in value:
        return False
    if value.lower() in {"configured", "redacted", "placeholder", "required", "optional"}:
        return False
    return bool(re.search(r"[A-Za-z]", value) and re.search(r"\d", value))


def find_secrets(text: str):
    hits = []
    for label, pat, grp in PATTERNS:
        for m in pat.finditer(text):
            value = m.group(grp)
            if value and PLACEHOLDER not in value and looks_like_secret(label, value):
                hits.append((label, value))
    return hits


def load_env():
    env = dict(os.environ)
    p = Path.home() / ".hermes" / ".env"
    if p.exists():
        for line in p.read_text().splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                k, v = line.split("=", 1)
                env.setdefault(k.strip(), v.strip().strip("'\""))
    return env


class OV:
    def __init__(self, endpoint, key):
        self.endpoint, self.key = endpoint.rstrip("/"), key

    def call(self, method, path, body=None, timeout=300):
        req = urllib.request.Request(
            self.endpoint + path, method=method,
            headers={"X-API-Key": self.key, "Content-Type": "application/json"},
            data=json.dumps(body, ensure_ascii=False).encode() if body is not None else None)
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.load(r).get("result")

    def ls(self, uri):
        return self.call("GET", "/api/v1/fs/ls?" + urllib.parse.urlencode({"uri": uri})) or []

    def read(self, uri):
        return self.call("GET", "/api/v1/content/read?" + urllib.parse.urlencode({"uri": uri, "raw": "true"}))

    def summary(self, uri, kind):
        """Generated directory abstract/overview (not listed by fs/ls)."""
        try:
            return self.call("GET", f"/api/v1/content/{kind}?" + urllib.parse.urlencode({"uri": uri})) or ""
        except urllib.error.HTTPError:
            return ""

    def write(self, uri, content):
        return self.call("POST", "/api/v1/content/write",
                         {"uri": uri, "content": content, "mode": "replace", "wait": True, "timeout": 240})


def walk(ov, uri, depth=0):
    try:
        items = ov.ls(uri)
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return
        raise
    yield "dir", uri
    for it in items:
        if it.get("isDir"):
            if depth < 10:
                yield from walk(ov, it["uri"], depth + 1)
        else:
            yield "file", it["uri"]


def main():
    dry = "--dry-run" in sys.argv
    env = load_env()
    ov = OV(env["OPENVIKING_ENDPOINT"], env["OPENVIKING_API_KEY"])
    user = env.get("OPENVIKING_USER", "default")
    roots = [f"viking://user/{user}/memories", f"viking://user/{user}/peers"]
    if "--roots" in sys.argv:
        roots = sys.argv[sys.argv.index("--roots") + 1].split(",")

    try:
        state = json.loads(STATE_FILE.read_text())
    except Exception:
        state = {"reported": []}
    reported = set(state.get("reported", []))

    fixed, manual = [], []
    for root in roots:
        for kind, uri in walk(ov, root):
            if kind == "dir":  # generated summaries can't be rewritten over the API: report once
                for summary in ("abstract", "overview"):
                    labels = sorted({label for label, _ in find_secrets(ov.summary(uri, summary))})
                    key = f"{uri}/.{summary}.md|{','.join(labels)}"
                    if labels and key not in reported:
                        manual.append((f"{uri}/.{summary}.md", labels))
                        reported.add(key)
                continue
            if not uri.endswith(".md"):
                continue
            text = ov.read(uri) or ""
            hits = find_secrets(text)
            if not hits:
                continue
            labels = sorted({label for label, _ in hits})
            if not dry:
                new = text
                for _, value in sorted(hits, key=lambda h: -len(h[1])):
                    new = new.replace(value, PLACEHOLDER)
                ov.write(uri, new)
            fixed.append((uri, labels))

    if not dry:
        STATE_FILE.write_text(json.dumps({"reported": sorted(reported)}))

    if fixed or manual:
        verb = "发现(未修改, dry-run)" if dry else "已自动脱敏"
        print(f"⚠️ OpenViking 记忆里发现凭据 ({len(fixed) + len(manual)} 处)")
        for uri, labels in fixed:
            print(f"- {verb}: {uri} [{', '.join(labels)}]")
        for uri, labels in manual:
            print(f"- 需手动处理(自动生成的摘要): {uri} [{', '.join(labels)}]")
        print("原值没有输出。请确认对应凭据是否需要轮换。")


if __name__ == "__main__":
    main()
